name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          tools: composer:v2
      - run: composer install --prefer-dist --no-progress
      - run: vendor/bin/phpcs
      - run: vendor/bin/psalm
      - run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml
